I_SRC=src/Install.cpp
E_SRC=src/Atom-Portable-Linux.cpp

Install: Install.cpp
	cd ..; g++ -g -o Install $(I_SRC)
	cd ..; chmod +x Install

Atom-Portable-Linux: Atom-Portable-Linux.cpp
	cd ..; g++ -g -o Atom-Portable-Linux $(E_SRC)
	cd ..; chmod +x Atom-Portable-Linux
