# Atom Portable Makefile
# Created by Andrew Davis (github.com/andrewsdavis)
# Licensed under MIT License
#
# Updated June 5, 2018

I_SRC=src/Install.cpp

Install: Install.cpp
	cd ..; g++ -g -o Install $(I_SRC)
	cd ..; chmod a+x Install
