# Quark Makefile
# Created by Andrew Davis (github.com/andrewsdavis)
# Licensed under MIT License
#
# Updated July, 1 2018

Install: Install.cpp
	cd ..; g++ -o Install src/Install.cpp
	cd ..; chmod u+x Install

Linux: Quark-Linux.cpp
	cd ..; g++ -o Quark-Linux src/Quark-Linux.cpp
	cd ..; chmod u+x Quark-Linux
